import express from "express";
import { createWorker, getWorkers, getWorkerById, updateWorker, deleteWorker } from "../controllers/worker.controller.js";
import { authMiddleware } from "../middleware/auth.js";
const router = express.Router();
router.post("/", authMiddleware, createWorker);
router.get("/", authMiddleware, getWorkers);
router.get("/:id", authMiddleware, getWorkerById);
router.put("/:id", authMiddleware, updateWorker);
router.delete("/:id", authMiddleware, deleteWorker);
export default router;
